Refactored `v` script

diff --git a/src/v b/src/v
--- a/src/v
+++ b/src/v
@@ -1,31 +1,44 @@
 #!/usr/bin/env bash
-#
-# Creates a Python virtualenv in ~/.virtualenv, with an optionally defined
-# virtualenv command and name.
-
-# Calling v with no arguments will result in a call to `pyvenv-3.4
-# ~/.virtualenv/default` if the virtualenv does not exist already.
-#
-# Usage: v [name] [virtualenv_command]
-#
 
 set -e
 
-# Place virtualenv's in ~/.virtualenv, or VIRTUAL_ENV_HOME
-VIRTUAL_ENV_HOME=${VIRTUAL_ENV_HOME:-$HOME/.virtualenv}
-
-# Use the second argument as the venv name, or 'default'
-export VIRTUAL_ENV="$VIRTUAL_ENV_HOME/${1:-default}"
-
-# Use pyvenv as the default virtualenv manager
-VIRTUAL_ENV_COMMAND=${VIRTUAL_ENV_COMMAND:-${2:-pyvenv-3.4}}
-
-# Check if the virtualenv exists, and create it if not
-if [[ ! -d $VIRTUAL_ENV || ! -f $VIRTUAL_ENV/bin/python ]]; then
-	"$VIRTUAL_ENV_COMMAND" "$VIRTUAL_ENV"
+if [[ $@ =~ --help || $@ =~ -h ]]; then
+    echo "Usage: v [name] [python]"
+    echo
+    echo "Activates or creates a virtualenv using virtualenvwrapper"
+    echo "Uses a default name of 'default' and the default python ($(which python))"
+    exit 1
 fi
 
+# Use 'default' as the default name
+# $1 -> V_DEFAULT -> 'default'
+V_NAME=${1:-$V_DEFAULT_NAME}
+V_NAME=${1:-default}
+
+# Use the system's python by default
+# $2 -> V_DEFAULT_PYTHON -> $(which python)
+V_PYTHON=${2:-$V_DEFAULT_PYTHON}
+V_PYTHON=${2:-$(which python)}
+
+# Select a directory virtualenvs will be placed in
+# This is also where hooks will be looked for
+# $V_HOME -> $WORKON_HOME -> $HOME/.virtualenv
+V_HOME=${V_HOME:=$WORKON_HOME}
+V_HOME=${V_HOME:=$HOME/.virtualenv}
+
+# Create the virtualenv if it does not already exist
+if [[ ! -d "$V_HOME/$V_NAME" || ! -f "$V_HOME/$V_NAME/bin/python" ]]; then
+    virtualenv -p "$V_PYTHON" "$V_HOME/$V_NAME"
+fi
+
+# Cleanup variable that aren't needed in the new shell
+# TODO: Is this nesscary?
+unset V_NAME
+unset V_PYTHON
+unset V_HOME
+
 # Start a new shell, with the virtualenv availible
+export VIRTUAL_ENV
 export PATH="$VIRTUAL_ENV/bin:$PATH"
 unset PYTHON_HOME
 exec "$SHELL"
